services:
  postgres-db:
    image: postgres:17-bookworm
    restart: unless-stopped
    shm_size: 128mb # Shared memory limit
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "127.0.0.1:5432:5432"

volumes:
  postgres_data:
